# Generated by Django 5.0.6 on 2024-05-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounditem',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
